### ISSUE TITLE
2.2.19 update

### ISSUE THREAD

**Issue by Azertooth** [jsimonetti/docker-gns3-server#13]
there's a way to update the image or you need to push it?

**Comment by jsimonetti** [comment]
I usually push a new version every once in a while. If a new GNS version is available, I have to manually push.
I will do this now.

**Comment by Azertooth** [comment]
i think the new version is requiring some new dependencies, it gives me this error when i start the container

```
gns3                 | time="2021-04-08T12:54:43.976781866Z" level=info msg="Loading containers: start."
gns3                 | Traceback (most recent call last):
gns3                 |   File "/usr/bin/gns3server", line 33, in <module>
gns3                 |     sys.exit(load_entry_point('gns3-server==2.2.17', 'console_scripts', 'gns3server')())
gns3                 |   File "/usr/bin/gns3server", line 25, in importlib_load_entry_point
gns3                 |     return next(matches).load()
gns3                 |   File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
gns3                 |     module = import_module(match.group('module'))
gns3                 |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
gns3                 |     return _bootstrap._gcd_import(name[level:], package, level)
gns3                 |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
gns3                 |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
gns3                 |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
gns3                 |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
gns3                 |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
gns3                 |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
gns3                 |   File "/usr/lib/python3.8/site-packages/gns3server/main.py", line 29, in <module>
gns3                 |     import gns3server.utils.get_resource
gns3                 |   File "/usr/lib/python3.8/site-packages/gns3server/utils/get_resource.py", line 19, in <module>
gns3                 |     import pkg_resources
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
gns3                 |     def _initialize_master_working_set():
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
gns3                 |     f(*args, **kwargs)
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
gns3                 |     working_set = WorkingSet._build_master()
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
gns3                 |     ws.require(__requires__)
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
gns3                 |     needed = self.resolve(parse_requirements(requirements))
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
gns3                 |     raise DistributionNotFound(req, requirers)
gns3                 | pkg_resources.DistributionNotFound: The 'distro>=1.3.0' distribution was not found and is required by gns3-server
gns3                 | time="2021-04-08T12:54:45.081127055Z" level=info msg="Starting up"
gns3                 | failed to start daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid
gns3                 | Traceback (most recent call last):
gns3                 |   File "/usr/bin/gns3server", line 33, in <module>
gns3                 |     sys.exit(load_entry_point('gns3-server==2.2.17', 'console_scripts', 'gns3server')())
gns3                 |   File "/usr/bin/gns3server", line 25, in importlib_load_entry_point
gns3                 |     return next(matches).load()
gns3                 |   File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
gns3                 |     module = import_module(match.group('module'))
gns3                 |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
gns3                 |     return _bootstrap._gcd_import(name[level:], package, level)
gns3                 |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
gns3                 |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
gns3                 |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
gns3                 |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
gns3                 |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
gns3                 |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
gns3                 |   File "/usr/lib/python3.8/site-packages/gns3server/main.py", line 29, in <module>
gns3                 |     import gns3server.utils.get_resource
gns3                 |   File "/usr/lib/python3.8/site-packages/gns3server/utils/get_resource.py", line 19, in <module>
gns3                 |     import pkg_resources
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
gns3                 |     def _initialize_master_working_set():
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
gns3                 |     f(*args, **kwargs)
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
gns3                 |     working_set = WorkingSet._build_master()
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
gns3                 |     ws.require(__requires__)
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
gns3                 |     needed = self.resolve(parse_requirements(requirements))
gns3                 |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
gns3                 |     raise DistributionNotFound(req, requirers)
gns3                 | pkg_resources.DistributionNotFound: The 'distro>=1.3.0' distribution was not found and is required by gns3-server
```

**Comment by jsimonetti** [comment]
Unfortunately it seems 2.2.19 is not yet in the alpine repositories. I'm looking into this further.

**Comment by jsimonetti** [comment]
I have flagged the package as out of date. There is nothing I can do at this point until the package maintainer updates the package version.
I'll keep this ticket open until it is updated.

**Comment by Azertooth** [comment]
meanwhile can you please create a dockerhub tag to rollback to a previous image version (2.2.17 or .18)?

**Comment by Azertooth** [comment]
erasing the container and start up again (with your latest docker hub image) the log gives me this

```
gns3                 | time="2021-04-08T20:15:38.325098894Z" level=info msg="Starting up"
gns3                 | time="2021-04-08T20:15:38.328995444Z" level=info msg="libcontainerd: started new containerd process" pid=27
gns3                 | time="2021-04-08T20:15:38.329068782Z" level=info msg="parsed scheme: \"unix\"" module=grpc
gns3                 | time="2021-04-08T20:15:38.329080925Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
gns3                 | time="2021-04-08T20:15:38.329114418Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
gns3                 | time="2021-04-08T20:15:38.329134746Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
gns3                 | Traceback (most recent call last):
gns3                 |   File "/usr/bin/gns3server", line 33, in <module>
gns3                 |     sys.exit(load_entry_point('gns3-server==2.2.17', 'console_scripts', 'gns3server')())
gns3                 |   File "/usr/bin/gns3server", line 22, in importlib_load_entry_point
gns3                 |     for entry_point in distribution(dist_name).entry_points
gns3                 |   File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
gns3                 |     return Distribution.from_name(distribution_name)
gns3                 |   File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
gns3                 |     raise PackageNotFoundError(name)
gns3                 | importlib.metadata.PackageNotFoundError: gns3-server
gns3                 | time="2021-04-08T20:15:39.177743009Z" level=info msg="Starting up"
gns3                 | failed to start daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid
gns3                 | Traceback (most recent call last):
gns3                 |   File "/usr/bin/gns3server", line 33, in <module>
gns3                 |     sys.exit(load_entry_point('gns3-server==2.2.17', 'console_scripts', 'gns3server')())
gns3                 |   File "/usr/bin/gns3server", line 22, in importlib_load_entry_point
gns3                 |     for entry_point in distribution(dist_name).entry_points
gns3                 |   File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
gns3                 |     return Distribution.from_name(distribution_name)
gns3                 |   File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
gns3                 |     raise PackageNotFoundError(name)
gns3                 | importlib.metadata.PackageNotFoundError: gns3-server
```

is normal that i see reference to 2.2.17?

`gns3                 |     sys.exit(load_entry_point('gns3-server==2.2.17', 'console_scripts', 'gns3server')())`

**Comment by jsimonetti** [comment]
> meanwhile can you please create a dockerhub tag to rollback to a previous image version (2.2.17 or .18)?

Hmm, this shouldn't happen. I'll see what I can do.

**Comment by jsimonetti** [comment]
Ok, so I have changed the build process to use pip to install gns3-server. This seems to work much better.
I'll see if I can make a github action to trigger this automatically at some point.
