### ISSUE TITLE
2.2.30 fails to launch

### ISSUE THREAD

**Issue by Kazaii** [jsimonetti/docker-gns3-server#40]
Recently pulled the latest image. Looks like it fails to startup.

Just an FYI,
Issue appears to be in gns3server itself, so I'll look closely and open a bug on their github.

```
[kazaii ~]$ gns3_server 
brctl: bridge virbr0: File exists
ip: RTNETLINK answers: File exists
time="2022-02-26T16:08:40.943158326Z" level=info msg="Starting up"
time="2022-02-26T16:08:40.943803724Z" level=info msg="libcontainerd: started new containerd process" pid=42
time="2022-02-26T16:08:40.943821267Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2022-02-26T16:08:40.943826687Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2022-02-26T16:08:40.943839892Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
time="2022-02-26T16:08:40.943849530Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2022-02-26T16:08:40Z" level=warning msg="deprecated version : `1`, please switch to version `2`"
time="2022-02-26T16:08:40.954411703Z" level=info msg="starting containerd" revision=1407cab509ff0d96baa4f0eb6ff9980270e6e620 version=v1.5.9
time="2022-02-26T16:08:40.971782029Z" level=info msg="loading plugin \"io.containerd.content.v1.content\"..." type=io.containerd.content.v1
time="2022-02-26T16:08:40.971828547Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.aufs\"..." type=io.containerd.snapshotter.v1
time="2022-02-26T16:08:40.972240267Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.aufs\"..." error="aufs is not supported (modprobe aufs failed: exit status 1 \"modprobe: can't change directory to '/lib/modules': No such file or directory\\n\"): skip plugin" type=io.containerd.snapshotter.v1
time="2022-02-26T16:08:40.972257530Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." type=io.containerd.snapshotter.v1
time="2022-02-26T16:08:40.972325697Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." error="path /data/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs (ext4) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
time="2022-02-26T16:08:40.972334213Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.devmapper\"..." type=io.containerd.snapshotter.v1
time="2022-02-26T16:08:40.972348801Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
time="2022-02-26T16:08:40.972355533Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.native\"..." type=io.containerd.snapshotter.v1
time="2022-02-26T16:08:40.972372886Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.overlayfs\"..." type=io.containerd.snapshotter.v1
time="2022-02-26T16:08:40.972438929Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.zfs\"..." type=io.containerd.snapshotter.v1
time="2022-02-26T16:08:40.972500404Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.zfs\"..." error="path /data/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
time="2022-02-26T16:08:40.972509822Z" level=info msg="loading plugin \"io.containerd.metadata.v1.bolt\"..." type=io.containerd.metadata.v1
time="2022-02-26T16:08:40.972521263Z" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
time="2022-02-26T16:08:40.972530040Z" level=info msg="metadata content store policy set" policy=shared
time="2022-02-26T16:08:40.972581506Z" level=info msg="loading plugin \"io.containerd.differ.v1.walking\"..." type=io.containerd.differ.v1
time="2022-02-26T16:08:40.972593158Z" level=info msg="loading plugin \"io.containerd.gc.v1.scheduler\"..." type=io.containerd.gc.v1
time="2022-02-26T16:08:40.972621100Z" level=info msg="loading plugin \"io.containerd.service.v1.introspection-service\"..." type=io.containerd.service.v1
time="2022-02-26T16:08:40.972645917Z" level=info msg="loading plugin \"io.containerd.service.v1.containers-service\"..." type=io.containerd.service.v1
time="2022-02-26T16:08:40.972659993Z" level=info msg="loading plugin \"io.containerd.service.v1.content-service\"..." type=io.containerd.service.v1
time="2022-02-26T16:08:40.972671465Z" level=info msg="loading plugin \"io.containerd.service.v1.diff-service\"..." type=io.containerd.service.v1
time="2022-02-26T16:08:40.972683347Z" level=info msg="loading plugin \"io.containerd.service.v1.images-service\"..." type=io.containerd.service.v1
time="2022-02-26T16:08:40.972697283Z" level=info msg="loading plugin \"io.containerd.service.v1.leases-service\"..." type=io.containerd.service.v1
time="2022-02-26T16:08:40.972711469Z" level=info msg="loading plugin \"io.containerd.service.v1.namespaces-service\"..." type=io.containerd.service.v1
time="2022-02-26T16:08:40.972722390Z" level=info msg="loading plugin \"io.containerd.service.v1.snapshots-service\"..." type=io.containerd.service.v1
time="2022-02-26T16:08:40.972733441Z" level=info msg="loading plugin \"io.containerd.runtime.v1.linux\"..." type=io.containerd.runtime.v1
time="2022-02-26T16:08:40.972819271Z" level=info msg="loading plugin \"io.containerd.runtime.v2.task\"..." type=io.containerd.runtime.v2
time="2022-02-26T16:08:40.972867281Z" level=info msg="loading plugin \"io.containerd.monitor.v1.cgroups\"..." type=io.containerd.monitor.v1
time="2022-02-26T16:08:40.973020528Z" level=info msg="loading plugin \"io.containerd.service.v1.tasks-service\"..." type=io.containerd.service.v1
time="2022-02-26T16:08:40.973033081Z" level=info msg="loading plugin \"io.containerd.internal.v1.restart\"..." type=io.containerd.internal.v1
time="2022-02-26T16:08:40.973066223Z" level=info msg="loading plugin \"io.containerd.grpc.v1.containers\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973076332Z" level=info msg="loading plugin \"io.containerd.grpc.v1.content\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973087874Z" level=info msg="loading plugin \"io.containerd.grpc.v1.diff\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973096240Z" level=info msg="loading plugin \"io.containerd.grpc.v1.events\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973105286Z" level=info msg="loading plugin \"io.containerd.grpc.v1.healthcheck\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973121096Z" level=info msg="loading plugin \"io.containerd.grpc.v1.images\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973131876Z" level=info msg="loading plugin \"io.containerd.grpc.v1.leases\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973143308Z" level=info msg="loading plugin \"io.containerd.grpc.v1.namespaces\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973153767Z" level=info msg="loading plugin \"io.containerd.internal.v1.opt\"..." type=io.containerd.internal.v1
time="2022-02-26T16:08:40.973262090Z" level=info msg="loading plugin \"io.containerd.grpc.v1.snapshots\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973276557Z" level=info msg="loading plugin \"io.containerd.grpc.v1.tasks\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973285023Z" level=info msg="loading plugin \"io.containerd.grpc.v1.version\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973294791Z" level=info msg="loading plugin \"io.containerd.grpc.v1.introspection\"..." type=io.containerd.grpc.v1
time="2022-02-26T16:08:40.973418583Z" level=info msg=serving... address=/var/run/docker/containerd/containerd-debug.sock
time="2022-02-26T16:08:40.973457746Z" level=info msg=serving... address=/var/run/docker/containerd/containerd.sock.ttrpc
time="2022-02-26T16:08:40.973490948Z" level=info msg=serving... address=/var/run/docker/containerd/containerd.sock
time="2022-02-26T16:08:40.973499124Z" level=info msg="containerd successfully booted in 0.019552s"
time="2022-02-26T16:08:40.976893848Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2022-02-26T16:08:40.976908355Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2022-02-26T16:08:40.976920648Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
time="2022-02-26T16:08:40.976927932Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2022-02-26T16:08:40.977327179Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2022-02-26T16:08:40.977337589Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2022-02-26T16:08:40.977347738Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
time="2022-02-26T16:08:40.977355703Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2022-02-26T16:08:40.980916929Z" level=info msg="Loading containers: start."
time="2022-02-26T16:08:41.017118367Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2022-02-26T16:08:41.032416564Z" level=info msg="Loading containers: done."
time="2022-02-26T16:08:41.036287700Z" level=info msg="Docker daemon" commit=847da184ad5048b27f5bdf9d53d070f731b43180 graphdriver(s)=vfs version=20.10.11
time="2022-02-26T16:08:41.036345639Z" level=info msg="Daemon has completed initialization"
time="2022-02-26T16:08:41.045228397Z" level=info msg="API listen on /var/run/docker.sock"
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 33, in <module>
    sys.exit(load_entry_point('gns3-server==2.2.30', 'console_scripts', 'gns3server')())
  File "/usr/lib/python3.9/site-packages/gns3server/main.py", line 82, in main
    from gns3server.run import run
  File "/usr/lib/python3.9/site-packages/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/usr/lib/python3.9/site-packages/gns3server/web/web_server.py", line 37, in <module>
    from .route import Route
  File "/usr/lib/python3.9/site-packages/gns3server/web/route.py", line 28, in <module>
    from ..controller.controller_error import ControllerError
  File "/usr/lib/python3.9/site-packages/gns3server/controller/__init__.py", line 27, in <module>
    from .project import Project
  File "/usr/lib/python3.9/site-packages/gns3server/controller/project.py", line 35, in <module>
    from .snapshot import Snapshot
  File "/usr/lib/python3.9/site-packages/gns3server/controller/snapshot.py", line 32, in <module>
    from .import_project import import_project
  File "/usr/lib/python3.9/site-packages/gns3server/controller/import_project.py", line 29, in <module>
    from .topology import load_topology
  File "/usr/lib/python3.9/site-packages/gns3server/controller/topology.py", line 31, in <module>
    from ..schemas.topology import TOPOLOGY_SCHEMA
  File "/usr/lib/python3.9/site-packages/gns3server/schemas/topology.py", line 22, in <module>
    from gns3server.schemas.compute import COMPUTE_OBJECT_SCHEMA
ImportError: cannot import name 'COMPUTE_OBJECT_SCHEMA' from 'gns3server.schemas.compute' (/usr/lib/python3.9/site-packages/gns3server/schemas/compute/__init__.py)
[kazaii~]$ 
```

**Comment by Kazaii** [comment]
Resolved by 2.2.31 release.

Thanks for the great container!

**Comment by jsimonetti** [comment]
Thanks for the heads up. I had not yet have time to check the latest update.
👍
