### ISSUE TITLE
DynamipsError

### ISSUE THREAD

**Issue by milenBG** [jsimonetti/docker-gns3-server#82]
Hi,

I've been using this for many releases, but since the last two I got following error:

2023-01-11 09:39:45 ERROR route.py:221 Node error detected: DynamipsError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 200, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/dynamips_vm_handler.py", line 72, in create
    vm = await dynamips_manager.create_node(request.json.pop("name"),
  File "/usr/lib/python3.10/site-packages/gns3server/compute/base_manager.py", line 259, in create_node
    await node.create()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/dynamips/nodes/c7200.py", line 91, in create
    await Router.create(self)
  File "/usr/lib/python3.10/site-packages/gns3server/compute/dynamips/nodes/router.py", line 213, in create
    self._hypervisor = await self.manager.start_new_hypervisor(working_dir=self.project.module_working_directory(self.manager.module_name.lower()))
  File "/usr/lib/python3.10/site-packages/gns3server/compute/dynamips/__init__.py", line 310, in start_new_hypervisor
    await hypervisor.connect()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/dynamips/dynamips_hypervisor.py", line 90, in connect
    raise DynamipsError("Couldn't connect to hypervisor on {}:{} :{}".format(host, self._port, last_exception))
gns3server.compute.dynamips.dynamips_error.DynamipsError: Couldn't connect to hypervisor on 127.0.0.1:33911 :[Errno 111] Connect call failed ('127.0.0.1', 33911)

**Comment by jsimonetti** [comment]
I would love to help but I have no idea how to reproduce this. I don't use dynamips myself.
A quick search for the error tells me that either dynamips is not running or it is running multiple times. A common theme around these errors appears to be (a problem with) permissions.

**Comment by jsimonetti** [comment]
This actually sounds like this issue: https://github.com/GNS3/dynamips/issues/62
We have to wait for v0.2.23 to becoma available. In the mean time you can use jsimonetti/gns3-server:2.2.35.1 version of the container.

**Comment by milenBG** [comment]
Yes, I already did that.
Thank you!

**Comment by milenBG** [comment]
This issue has been resolved. But now the image lacks util-linux package which provides "script" command used by docker containers. Any way you can close this issue.

**Comment by jsimonetti** [comment]
Hi,
Thank you for letting me know. I have added util-linux as additional dependency. This should resolve the missing 'script' command. Please open a new issue if you find anything else is missing too.
Thank you!
